// START product
export const GET_PRODUCTS_BY_FILTER_REQUEST = 'GET_PRODUCTS_BY_FILTER_REQUEST';
export const GET_PRODUCTS_BY_FILTER_SUCCESS = 'GET_PRODUCTS_BY_FILTER_SUCCESS';
export const GET_PRODUCTS_BY_FILTER_FAILURE = 'GET_PRODUCTS_BY_FILTER_FAILURE';

export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE';

// END product

// START cart
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const PAYMENT = 'PAYMENT';

export const SHOW_SUCCESS_PAYMENT_MODAL = 'SHOW_SUCCESS_PAYMENT_MODAL';
export const HIDE_SUCCESS_PAYMENT_MODAL = 'HIDE_SUCCESS_PAYMENT_MODAL';

// END cart
